### ISSUE TITLE
Leading digits in local names not supported.

### ISSUE THREAD

**Issue by estaub** [AKSW/Xturtle#58]
While earlier drafts did not, the final [RDF 1.1 Turtle Recommendation](http://www.w3.org/TR/2014/REC-turtle-20140225/#sec-grammar-grammar) allows leading digits in local names (i.e., names after a prefix and colon).  See especially terminal production PN_LOCAL.

xturtle does not support this.  There are probably other grammar changes in the final recommendation that need tweaking for, too.

FWIW, I ran into this from the [RDF Data Cube Vocabulary](http://www.w3.org/TR/2014/REC-vocab-data-cube-20140116/#metadata-categorization), in section 9.1, referencing Turtle file http://purl.org/linked-data/sdmx/2009/subject#.

**Comment by nittka** [comment]
Further improvements have been made, see the latest snapshot on my homepage.
