### ISSUE TITLE
rdf:_1 could not find definition

### ISSUE THREAD

**Issue by MichaelHerne** [AKSW/Xturtle#59]
Hi all,
I played a day with xturtle and get a problem with RDF collections. xturtle cant find definitions for rdf:_1, rdf:_2 and so on. But its the only way to define container membership properties.

My example: 

@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix ex: <http://www.example.com#>.

ex:letter rdf:type rdf:Bag;
	rdf:_1 "a";
	rdf:_2 "b".

**Comment by nittka** [comment]
A third possibility is writing rdf:_1 as full IRI. Reopen the issue, in case you are not happy with any of the suggestions and have a better idea.
