### ISSUE TITLE
Error parsing general axioms in ttl files

### ISSUE THREAD

**Issue by AlexanderWillner** [AKSW/Xturtle#61]
Version: 4.4.1 (eclipse) / 1.0.1 (Xturtle plugin)

Steps that will reproduce the problem?
1. Open a ttl file in eclipse in the Xturtle view
2. Add an axiom to the file

What is the expected result?
Everything is fine.

What happens instead?
Turtle states an error: "no viable alternative at input '['"

Possible workaround:
?

Any additional information:
How an axiom looks like:
```
[ rdf:type owl:AllDisjointClasses ;
  owl:members ( :Foo
                :Bar
              )
] .
```

**Comment by nittka** [comment]
At first, I was wondering how your example axiom fit the triple definition at all, but then I noted that for blank nodes the predicateObjectList is optional. In the current version of the Xturtle grammar it is mandatory, so there is no workaround.
Maybe it was not in the language draft this implementation was based on, maybe I missed it to begin with...

I plan some work on the grammar, anyway, so I will try to include this case as well. I cannot make any promises on the timeline, though.

**Comment by AlexanderWillner** [comment]
Thanks for the update. It's actually part of an ontology that was saved using Protégé/OWL-API. So I assume this way of encoding axioms is rather typical.

**Comment by nittka** [comment]
Please try out the latest snapshot plugins from http://www.nittka.de/download/xturtle/
Thanks for the feedback.

**Comment by AlexanderWillner** [comment]
Nice. Not sure how to test though. Can't install via "Dropin", "Archive", "Local" or by manually replacing the existing jars...

**Comment by nittka** [comment]
Placing the jars in the dropins folder of an eclipse where Xturtle is *not* installed via the update site should work... Have you tried that?

**Comment by AlexanderWillner** [comment]
Well, doesn't work for me (see attached screenshot), but I'll just wait until I can download the new version from the official update site (version 1.0.2 I'd guess). Thanks again.

![screen shot 2015-01-27 at 09 04 27](https://cloud.githubusercontent.com/assets/307605/5915264/c03c7cba-a603-11e4-8bd5-6879bb2ea04c.png)

**Comment by nittka** [comment]
It looks to me that Xtext is not installed but this is a precondition. Could you copy the eclipse where Xturtle 1.0.1 works, deinstall Xturtle and put the plugins into the dropins folder. This should work.

**Comment by AlexanderWillner** [comment]
This was what I did. Anyway, it's working now (after I installed the Xtext SDK).
I can confirm that the new version does not show the error messages anymore :+1:
