### ISSUE TITLE
turtle validation error on ´<<´

### ISSUE THREAD

**Issue by seebi** [AKSW/Xturtle#67]
Currently, Xturtle does not throw an error when parsing this document:

```
<<http://example.org> a <http://example.org/Domain> .
```

rapper throws this:

```
rapper: Parsing URI file:///.../error.ttl with parser turtle
rapper: Error - URI file:///...error.ttl:1 - syntax error at '<'
rapper: Parsing returned 0 triples
```

**Comment by nittka** [comment]
Indeed validation for IRI syntax is not yet implemented, this also includes white spaces and escapings. Currently, everything between '<' and '>' is eaten up and stored as "valid" IRI.
I would implement that as validation on saving for performance reasons.

**Comment by nittka** [comment]
Syntax validation with respect to the RegEx in the Turtle grammar definition is added. Validation for bad escape sequences has not yet been added (an IRI containing `\u0020` is not marked as error although the escaped character represents space).
