### ISSUE TITLE
Editor cannot find definition for owl:Class

### ISSUE THREAD

**Issue by kjkeefe** [AKSW/Xturtle#73]
Do I need to do something to fetch remote resources?

**Comment by kjkeefe** [comment]
![Screen Shot 2020-09-08 at 9 27 02 PM](https://user-images.githubusercontent.com/13408406/92547475-93be1180-f21a-11ea-8ab5-7835b9b6156f.png)

**Comment by nittka** [comment]
Sorry that the readme and the wiki are not explicit enough. In the scope section of the introduction(https://github.com/AKSW/Xturtle/wiki/Project-Brainstorming#scope) we state that all needed vocabulary must be present in the workspace. We do not dynamically load (and transform) definitions from the web.

The repository itself contains a number of prepared vocabulary files (https://github.com/AKSW/Xturtle/tree/develop/vocabularies), xturtle.core also contains an owl.ttl (https://github.com/AKSW/Xturtle/blob/develop/vocabularies/xturtle.core/owl.ttl).

Import the appropriate vocabulary projects into your workspace and make them available to the project containing the example.ttl (https://github.com/AKSW/Xturtle/wiki/Usage).

**Comment by kjkeefe** [comment]
Thank you for the pointer! I fixed almost all of my issues. Can you tell me how to deal with XMLSchema? 

I need the anyURI type. I have put XMLSchema.xsd in the workspace, but I am guessing that that file isn't being indexed. Does it only look for ttl files? Is there a ttl version of XMLSchema somewhere?

Thanks!

**Comment by nittka** [comment]
Yes, only ttl files are supported. XMLSchema is defined in https://github.com/AKSW/Xturtle/blob/develop/vocabularies/xturtle.core/xsd.ttl

**Comment by nittka** [comment]
I have updated the limitations on the wiki start page accordingly.
